<?php foreach ($products as $prod) { ?>
    <div class="panel panel-default">
        <a href="<?php echo $this->url('product', array('action' => 'view', 'id' => $prod->product_id))?>" class="panel-body">
            <div class="col-xs-6">
                <img src="img/<?php echo $prod->product_id ?>.png" alt="<?php echo $prod->product_name ?>" height="300px" width="300px">
            </div>
            <div class="col-xs-6">
                <strong>Product Name: </strong><?php echo $prod->product_name ?><br>
                <strong>Description: </strong><?php echo $prod->product_desc ?><br>
                <strong>Price: </strong><strong><?php echo $prod->price ?><br></strong>
            </div>
        </a>
    </div>
<?php } ?>
